Repository Maia-Cochran/rancid-tomatillos, pull requests merged in 2022-09, with the labels that each got.

#30 Feat: add error handling
  src/components/App/App.js
  src/components/InternalServerError/InternalServerError.css
  src/components/InternalServerError/InternalServerError.js
  src/components/MovieContainer/MovieContainer.css
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.js
  src/components/Status/Status.css
  src/components/Status/Status.js
Labels: Error Handling

#32 Add Switch to App and adjust style of movie container
  src/api-calls.js
  src/components/App/App.js
  src/components/InternalServerError/InternalServerError.js
  src/components/Modal/Modal.js
  src/components/MovieContainer/MovieContainer.css
  src/components/MovieContainer/MovieContainer.js
  src/components/NotFound/NotFound.js
  src/components/Status/Status.js
Labels: enhancement

#33 Add first cypress tests for MovieContainer
  cypress.config.js
  cypress/e2e/error_handling.cy.js
  cypress/e2e/modal.cy.js
  cypress/e2e/movie_container.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: Testing

#34 Maia/cypress modal
  cypress/e2e/modal.cy.js
  cypress/e2e/movie_container.cy.js
  src/components/App/App.test.js
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
Labels: Testing

#35 Add iframe element to render videos to single movie details page
  src/components/Card/Card.css
  src/components/Modal/Modal.js
  src/components/MovieContainer/MovieContainer.css
Labels: enhancement

#36 Add buttons to cycle through videos for a specific movie
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
Labels: enhancement, UI, Styling, Spicy

#37 Refactor: change modal to singlemovie
  cypress/e2e/movie_container.cy.js
  cypress/e2e/single_movie.js
  src/components/App/App.js
  src/components/MovieContainer/MovieContainer.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
Labels: Testing, refactor

#38 Add css reset to prevent weird margins, also re-design SingleMovie page
  src/components/Card/Card.css
  src/components/Header/Header.css
  src/components/MovieContainer/MovieContainer.css
  src/components/MovieContainer/MovieContainer.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
  src/index.css
Labels: Styling

#41 Chantal/carousel round 2
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/InternalServerError/InternalServerError.js
  src/components/MovieContainer/MovieContainer.css
  src/components/MovieContainer/MovieContainer.js
  src/components/NotFound/NotFound.js
  src/components/SlideNextButton/SlideNextButton.css
  src/components/SlideNextButton/SlideNextButton.js
  src/index.js
Labels: enhancement, UI, Accessibility, functional-component, refactor

#43 Tom/main page styling
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/MovieContainer/MovieContainer.css
  src/components/MovieContainer/MovieContainer.js
  src/components/SingleMovie/SingleMovie.css
  src/index.css
  src/index.js
Labels: UI, Styling

#44 Update cypress tests for redesigned main page
  cypress/e2e/movie_container.cy.js
  cypress/e2e/single_movie.cy.js
  package-lock.json
  package.json
  src/components/MovieContainer/MovieContainer.js
Labels: Testing

#45 Chantal/trailor swiper
  package-lock.json
  package.json
  src/components/Carousel/Carousel.css
  src/components/Carousel/Carousel.js
  src/components/MovieContainer/MovieContainer.css
  src/components/MovieContainer/MovieContainer.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
  src/components/SlideNextButton/SlideNextButton.css
  src/components/SlideNextButton/SlideNextButton.js
Labels: enhancement, Styling

#46 Refactor swiper naming conventions to reflect changes
  cypress/e2e/movie_container.cy.js
Labels: Testing

#47 Maia/refactor single movie test suite
  cypress/e2e/single_movie.cy.js
  src/components/SingleMovie/SingleMovie.js
Labels: Testing

#48 Add tests for Not Found component with Cypress
  cypress/e2e/error_handling.cy.js
Labels: Testing

#50 Maia/refactor test suites
  cypress/e2e/error_handling.cy.js
Labels: Testing

#51 Maia/refactor readme
  README.md
  public/index.html
  src/Ideas
  src/api-calls.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Card/Card.test.js
  src/components/InternalServerError/InternalServerError.css
  src/components/InternalServerError/InternalServerError.js
  src/components/MovieContainer/MovieContainer.js
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.js
  src/components/SingleMovie/SingleMovie.css
  src/components/SingleMovie/SingleMovie.js
  src/components/Status/Status.css
  src/components/Status/Status.js
  src/index.css
Labels: UI, Styling

#53 Chantal/response page image
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.js
  src/images/tom-splt.png
  src/images/tomato-splt-sm.svg
Labels: enhancement, UI, Styling, Error Handling, refactor
