Repository Maia-Cochran/rancid-tomatillos, pull requests merged in 2022-08, with the labels that each got.

#4 Chantal/movie container component
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/rancid-tomatillos.png
  src/App.css
  src/App.js
  src/App.test.js
  src/Ideas
  src/components/App/App.css
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/Card/Card.test.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/MovieContainer/MovieContainer.css
  src/components/MovieContainer/MovieContainer.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
Labels: good first issue, UI, class-component, functional-component

#5 Maia/add data file
  src/components/App/App.js
  src/data.js
Labels: Data

#15 Add movieContainer and Card components and some css for them
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Card/Card.js
  src/components/MovieContainer/MovieContainer.css
  src/components/MovieContainer/MovieContainer.js
  src/images/rancid-tomatillos.png
Labels: functional-component

#17 Tom/select a movie method
  public/index.html
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/MovieContainer/MovieContainer.js
Labels: enhancement

#18 Feat: fetch API data
  src/api-calls.js
  src/components/App/App.js
Labels: Fetch API

#19 Add styling to movie container section
  src/components/App/App.css
  src/components/App/App.js
  src/components/Card/Card.css
  src/components/Header/Header.css
  src/components/MovieContainer/MovieContainer.css
  src/index.css
Labels: Styling

#20 Maia/build modal new
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/ReactModalInner/ReactModalInner.css
  src/components/ReactModalInner/ReactModalInner.js
Labels: help wanted

#22 Feat: created modal functionality
  src/api-calls.js
  src/components/App/App.js
  src/components/Modal/Modal.js
Labels: enhancement, functional-component

#26 Maia/modal css
  package-lock.json
  package.json
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
Labels: question, UI, Styling

#27 Tom/react router
  package-lock.json
  package.json
  src/api-calls.js
  src/components/App/App.js
  src/components/Card/Card.js
  src/components/Header/Header.js
  src/components/Modal/Modal.js
  src/components/MovieContainer/MovieContainer.js
  src/index.js
Labels: class-component

#29 Maia/functioning modal style
  src/components/Modal/Modal.css
  src/components/Modal/Modal.js
  src/components/MovieContainer/MovieContainer.css
Labels: Accessibility, Styling, class-component, Data
